stm32-rs/stm32f3xx-hal

Cargo.toml, src/gpio.rs
=> Update embedded-hal and use v2 pin API

Cargo.toml, src/timer.rs
Tested out with https://github.com/dfrankland/proton-c using USB HID!
=> Fix up timers and make the code more consistent with the stm32f1xx-hal crate

CHANGELOG.md
Following up on #56 to also update the changelog.
=> Update changelog with MonoTimer frequency fix

src/gpio.rs, src/i2c.rs, src/pwm.rs, src/rcc.rs, src/serial.rs, src/spi.rs, src/timer.rs
Tends towards #36, removing some side-effects.
might have fixed some bugs that where not triggered until now.
Note that some side effects could be useful for the code working as intended, however
> Explicit is better than implicit.
=> Justify write

CHANGELOG.md, Cargo.toml
Closes https://github.com/stm32-rs/stm32f3xx-hal/issues/110
=> Bump version

CHANGELOG.md, src/rcc.rs
=> Remove divisor check for HSE PRE_DIV

src/i2c.rs
I've just found my silly copy-paste mistake in #154 😢
=> Fix for #154

.github/workflows/ci.yml, .markdownlint.yml, CHANGELOG.md, Cargo.toml, README.md, codegen/README.md, examples/adc.rs, examples/gpio_erased.rs, src/adc.rs, src/can.rs, src/dma.rs, src/gpio.rs, src/i2c.rs, src/pwm.rs, src/spi.rs, src/usb.rs, src/watchdog.rs
=> Release v0.6.0

Cargo.toml, src/dma.rs, src/gpio.rs
=> Use paste! instead of doc_comment!

.github/workflows/ci.yml, CHANGELOG.md, src/adc.rs, src/can.rs, src/dma.rs, src/gpio.rs, src/i2c.rs, src/pwm.rs, src/usb.rs, src/watchdog.rs
Get's me every time. :see_no_evil: 
This deserves a lint running in CI.
=> Fixup broken link in changelog

.github/workflows/ci.yml, src/adc.rs, src/delay.rs, src/dma.rs, src/flash.rs, src/gpio.rs, src/i2c.rs, src/lib.rs, src/prelude.rs, src/rcc.rs, src/rtc.rs, src/serial.rs, src/spi.rs, src/syscfg.rs, src/timer.rs, src/usb.rs, src/watchdog.rs
Some minor formatting improvements mostly.
=> Improve doc

CHANGELOG.md, RELEASE_PROCESS.md, release.toml
=> Add configuration for cargo-release

CHANGELOG.md, codegen/Cargo.toml, release.toml
- Fix missing '-' in CHANGELOG header
- Make sure to not publish codegen
=> Improve release process

.github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, testsuite/README.md
This should hopefully clear up some confusion upfront for
first-time contributors and also lays down a kind of "roadmap"
how this crate should go forward.
=> Add contributing.md

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, examples/serial_echo_rtic.rs, src/lib.rs, src/serial.rs, testsuite/Cargo.toml, testsuite/tests/uart.rs
=> Rework serial (interrupt) events 

CHANGELOG.md, src/timer.rs
Change timer interrupt API to be more in line with #253
=> Timer interrupt

README.md
This is to prevent problems like these: #268
=> Mention resolver = "2" in README

CHANGELOG.md, src/adc.rs, src/delay.rs, src/i2c.rs, src/rtc.rs, src/serial.rs, src/spi.rs, src/timer.rs, src/watchdog.rs
=> Add way to modify underlying peripheral

examples/serial_echo_rtic.rs
I found the `serial_echo_rtic.rs` example to be not completely self-explanatory. This PR attempts to add info that I would've found helpful while reading/using it :)
=> examples/serial_echo_rtic.rs: add more explanations; usage

CHANGELOG.md, Cargo.toml, examples/serial_echo_rtic.rs, src/pwm.rs, src/timer/interrupts.rs, testsuite/tests/adc.rs, testsuite/tests/timer.rs
=> Upgrade to stm32f3 v0.14.0

src/adc.rs, src/timer.rs
This addresses lints and Clippy warnings and should make CI pass again.
=> Fix warnings
