stm32-rs/stm32f3xx-hal

Cargo.toml
src/gpio.rs

Based on the original pull request by @octycs
cf. https://github.com/japaric/stm32f30x-hal/pull/16
Let me know if you have any feedback

Implement InputPin GPIO traits

---

src/i2c.rs

I2C communications are not working because the address is not correctly written in SADD (CR2).
The address must be shifted because the LSB of SADD is ignore in 7 bits mode and we are only managing 7 bit mode.
_Extract for CR2 register from documentation :_
Bits 7:1 SADD[7:1]: Slave address bit 7:1 (master mode)
In 7-bit addressing mode (ADD10 = 0):
These bits should be written with the 7-bit slave address to be sent
In 10-bit addressing mode (ADD10 = 1):
These bits should be written with bits 7:1 of the slave address to be sent.
Note: Changing these bits when the START bit is set is not allowed.
Bit 0 SADD0: Slave address bit 0 (master mode)
In 7-bit addressing mode (ADD10 = 0):
This bit is don’t care
In 10-bit addressing mode (ADD10 = 1):
This bit should be written with bit 0 of the …

I2C communication not wotking because of wrong address

---

Cargo.toml
src/gpio.rs

This PR adds support for GPIO configuration with AF14, which is needed for USB peripheral.

Add support for GPIO AF14, bump version

---

Cargo.toml
examples/toggle.rs
src/gpio.rs
src/prelude.rs

I tested it on the STM32F303 / STM32DISCOVERY Board, with the method provided in the example.

Add StatefulOutputPin and ToggleableOutputPin

---

src/gpio.rs

Allow dead code for the AFRL impl, and document the exact cases that require it.

Suppress dead code warning in gpio module.

---

src/gpio.rs

I noticed, that the `into_floating_input` method went missing. My project, which used it before did not compile. Something like this would'nt compile anymore. 
```rust
fn main() -> ! {
let dp = stm32::Peripherals::take().unwrap();
let mut gpioa = dp.GPIOA.split(&mut rcc.ahb);
let user_button = gpioa
.pa0
.into_floating_input(&mut gpioa.moder, &mut gpioa.pupdr);
loop {}
}
```
And when poking around, I saw the implementation was accidentally deleted in this commit:
https://github.com/stm32-rs/stm32f3xx-hal/pull/21/commits/684e7bd8c1a1f037ef3b0a6d63609de06bea043b

Readd `into_floating_input`

---

src/gpio.rs

This is necessary when you're using a DAC.

Add analog gpio mode

---

src/rcc.rs

This allows us to use a 72mhz sysclk on stm32f303.  In the current
version, this is artificially locked to 64mhz by the hal (since the hal will never change pwm sources).
I also think this fixes a bug where we would never actually use the hse as the pll source.

Support devices with 2-bit PLLSRC fields

---

.travis.yml
src/prelude.rs
src/rcc.rs

As this crate is almost rustfmt compatible, why don't we add it to the CI?
Also, this moves the rustup invocations to `install` which travis provides.
This make no difference now, but if we add more ci jobs with `matrix`, rustup wouldn't be called for every job.

Add rustfmt

---

CHANGELOG.md
Cargo.toml
examples/spi.rs
src/spi.rs

I noticed, that the SPI is not working on my STM Discovery Board.
With some debugging, I first found out, that the SPI is for example not initialized as master.
I used [PyCortexMDebug](https://github.com/bnahill/PyCortexMDebug), to see if
the registers are correctly set in combination with the svd file provided by
[stm32-rs](https://github.com/stm32-rs/stm32-rs/blob/master/svd/vendor/en.stm32f3_svd.zip).
I did provide a minimal example, to reproduce these steps. Ideally, this example
should be extended, to be helpful for newcomers and not just a configuration
example, without using the SPI. Something like connecting MOSI and MISO to echo
the output and do `assert_eq!` or similar.
`openocd.cfg`:
```cfg
source [find interface/stlink.cfg]
source [find target/stm32f3x.cfg]
```
```bash
openocd …
```

Fix spi initialization

---

CHANGELOG.md
Cargo.toml
src/i2c.rs
src/rcc.rs
src/spi.rs
src/timer.rs
src/usb.rs

This PR updates to `stm32f3 v0.9`.
Also, register access methods where upgraded to use the variant based methods, introduced in the svd2rust version 16 (see the [CHANGELOG](https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#added)).
I reduced the scope to change only the peripherals, where it worked seamless.
I've prepared PR's for the missing peripheral modules, but I did'nt include them, as `stm32f3` does not provide the variant methods for all stm32f3 devices, because they are'nt documented yet.

Update stm32f3 to 0.9

---

.travis.yml
CHANGELOG.md
src/spi.rs

The comments indicate that the code is attempting to set the SPI order to MSB first, however it actually sets it to LSB first. Since most devices are MSB first, this is the correct choice.
Closes #59.

Fix SPI initialization to be MSB first

---

Cargo.toml

With the last release, the documentation would not build on docs.rs
Setting the `default-target` to `"x86_64-unknown-linux-gnu"` should fix this. 
Can be reverted, when https://github.com/rust-lang/docs.rs/issues/563 is resolved.
Fixes https://github.com/stm32-rs/stm32f3xx-hal/issues/46

Fix docsrs build

---

src/time.rs

The `MonoTimer` internally counts the cycles of the Cortex core. So unless I am missing something, its frequency is HCLK, not SYSCLK, according to the reference manual. I also verified this as true on an STM32F303VC.
Without this fix `MonoTimer` is only usable for timing measurements if HCLK equals SYSCLK.

Fix MonoTimer's frequency

---

CHANGELOG.md
Cargo.toml

Some PR's could benefit from this change
And I do think, that it does more sense to split this out of #42. #42 could introduce bugs and it is a higher risk to merge it, just for the sake of updating stm32f3. 
This PR should have no risk, because it does not touch any of the existing code.

Update stm32f3 to v0.10.0

---

CHANGELOG.md
src/i2c.rs

- Use automatic mode for autoend with `Read`
- Check for variant success first in `busy_wait` macro
Tested with the following embedded hal i2c drivers:
- bmp280 (barometer)
- em7180 (imu/ahrs)
- bno080 (ahrs wip)

Fixes for i2c Read 

---

src/time.rs

Change the `Into` traits to `From` traits, as `Into` is automatically available if `From` is implemented. `Into` should only be used if  `From` can not be implemented due to the orphan rule.

Change Into trait to From trait

---

Cargo.toml

There was recently a change to docs.rs to allow tier 2 targets, such as thumbv7em-none-eabihf. In the process, the “set default target to x86_64” trick broke.

Fix docs.rs build

---

examples/pwm.rs
examples/spi.rs
examples/toggle.rs
examples/usb_serial.rs

`use panic_semihost as _` is more in line with 2018 edition.

Remove "extern crate" in favor "use"

---

CHANGELOG.md
src/gpio.rs

After reset, the debug GPIO pins (PA13, PA14, PA15, PB3, PB4) are in AF0
mode. This PR fixes the `gpio` code to reflect this.
I've checked all the relevant RMs to verify this. It's easiest to just look at the reset values of the `GPIOx_MODER` register. Also all the RMs say "The debug pins are in AF pull-up/pull-down after reset".

Fix default mode of debug GPIO pins

---

examples/pwm.rs

Hi, the pwm example causes a panic on TIM2 configuration, in the call to `tim2()`. Root cause is that the default 4 MHz SYSCLK isn't fast enough to deliver the resolution and frequency requested (TIM2 needs a clock of at least 160_000 * 50 Hz = 8 MHz, and this can't be greater than SYSCLK). The actual panic occurs [here](https://github.com/stm32-rs/stm32f3xx-hal/blob/master/src/pwm.rs#L468) when `prescale_factor=0`. The easy fix is to bump SYSCLK to at least 8 MHz.
I also removed PB3 and PB7 from the set of output pins, since on the F3 Discovery board these (may) be used for other things. PB3 may be attached to the SWO line of the debugger port (if solder bridge SB10 is on), and monkeying with that pin kills ITM debugging. PB7 is attached to the I2C1 SDA line of the LSM303DLHC …

Fixes to prevent panic setting up TIM2 in pwm example

---

src/lib.rs
src/time.rs
src/watchdog.rs

This is based on similar implementations from the other stm32 crates, with some minor modifications to support the f3 specifics.
I have tested this on the stm32f303 but haven't checked the exact LSI frequencies and such for the other devices though I assume they are the same.

Independent watchdog

---

Cargo.toml

This PR changes the version specifications in the Cargo.toml:
- `"0.y.z"` -> `"0.y"`
- `"x.y.z"` -> `"x"`
This does not functionally change anything, since version strings
without any operators default to the caret requirement anyway ([see Cargo docs][1]).
This changes just makes it obvious.
[1]: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

Clean up dependency versions in Cargo.toml

---

CHANGELOG.md
src/rcc.rs

This PR updates all register accesses to variants in the rcc and similar modules.
I took the opportunity to reorganize the usb rcc initialization to play nicer with variants.
~~I'm not really happy about:~~
https://github.com/stm32-rs/stm32f3xx-hal/blob/e09a86622c9dc9d421bd53f24f7ebc982505417a/src/rcc.rs#L292
~~but it works.~~
~~I wish [stm32rs](https://github.com/stm32-rs/stm32-rs) would implement `From<HPRE_A> -> u8`. I guess this is a [svd2rust](https://github.com/rust-embedded/svd2rust) thing.~~
Now using `u8::from()` for casting.

Add rcc variants

---

CHANGELOG.md
Cargo.toml
src/rcc.rs

Remove now unneeded unsafe from the flash state configuration in `src/rcc.rs` and use `HCLK` instead of `SYSCLK` as the reference manual suggests.

Update stm32f3 to v0.11.0

---

CHANGELOG.md
examples/pwm.rs
examples/spi.rs
examples/toggle.rs
examples/usb_serial.rs
src/flash.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/prelude.rs
src/pwm.rs
src/rcc.rs
src/serial.rs
src/spi.rs
src/timer.rs
src/usb.rs
src/watchdog.rs

This checks one of the boxes listed in the [new chapter](https://rust-embedded.github.io/book/design-patterns/index.html) of the embedded book. 
[C-REEXPORT-PAC](https://rust-embedded.github.io/book/design-patterns/hal/interoperability.html#c-reexport-pac)

Rename stm32 to pac

---

src/gpio.rs

This PR upgrades to variant methods for the gpio module.
Doing this I had to extend the macro invocations significantly.
Also, I found no elegant way to apply this to the downgradable pins, as the pin register field access is determined via
"runtime".
https://github.com/rust-embedded/svd2rust/pull/400 could help with that.
Also, for the `stm32f3x8` and `stm32f373` series, this can not be applied right now, as they are missing a gpio documentation.
https://github.com/stm32-rs/stm32-rs/pull/321 will add these.

Use gpio variants

---

CHANGELOG.md
src/gpio.rs
src/rcc.rs

Forked from #105 and added some cleanup.
Resolves #84.
Once this is merged we can close both #88 and #105.

Implement InputPin for Output<OpenDrain> pins

---

CHANGELOG.md
Cargo.toml
examples/serial_dma.rs
src/dma.rs
src/lib.rs
src/prelude.rs
src/serial.rs

This PR is the first part of an effort to add DMA support to this crate (see issue #66). It adds initial support for DMA, including:
- A `DmaExt` extension trait that splits a DMA peripheral into individual channels
- A `Transfer` abstraction that provides memory-safe one-shot DMA transfers
- New methods on serial receivers and transmitters to read/write data via DMA
This works only on STM32F303 devices for now.

Initial DMA support

---

CHANGELOG.md
Cargo.toml
examples/adc.rs
src/adc.rs
src/lib.rs

Add ADC usage (for `stm32f303` devices)

---

src/rcc.rs

I stumbled upon this code again and thought I could make it a bit more readable.

Use match instead of nested `if let`

---

CHANGELOG.md
src/spi.rs

Some devices (eg SD cards) require the initialization to be done a at a lower frequency and allow the frequency to be later increased. Thus a re-clock functionality has been added. The tm4c123x-hal also does this.

Add reclock functionality for SPI

---

.github/workflows/ci.yml

The previous CI executed the `cargo check` command with the `--examples` flag. The intention was to check both the library itself and the examples. However, for most MCU versions we don't provide any examples, they are explicitly feature gated to stm32f303 devices. In these cases cargo decides that there is nothing to do, so it also doesn't check the library itself, effectively disabling checking for most MCU families.
We instead want to use the `--all-features` flag. From the cargo docs:
"Check all targets. This is equivalent to specifying `--lib --bins --tests --benches --examples`."
However, this doesn't work unfortunately since cargo is complaining about a missing crate "test" for the thumb7em-none-eabihf target. So instead we explicitly use `--lib --examples`.
This PR also updates …

Fix Github Actions CI config

---

Cargo.toml
src/dma.rs

This PR removes the DMA traits from the HAL code and instead replaces them with the ones from the [embedded-dma crate](https://crates.io/crates/embedded-dma). Those traits are basically the same, so this is only a code move, no functional changes.

Migrate to traits from embedded-dma crate

---

CHANGELOG.md
src/dma.rs
src/lib.rs
src/prelude.rs
src/serial.rs

Enable DMA for USART on STM32F302 devices

---

CHANGELOG.md
src/i2c.rs

This adds support for I2C write and read of more than 255 bytes, and I2C write of 0 byte.

Support I2C transfers of more than 255 bytes

---

CHANGELOG.md
src/rcc.rs

Fix #142.
However, APIs for the same thing are vary in all stm32-rs HALs... Are there any suggestions?
* this PR
```rust
let clocks = rcc.cfgr/* .use_hse_crystal(8.mhz()) */.use_hse_bypass(8.mhz()).enable_css().freeze();
```
* f0xx
```rust
let rcc = dp.RCC.configure().hse(HSEClock::new(8.mhz(), HSEBypassMode::Bypassed)).freeze(&mut dp.FLASH);
```
* f7xx
```rust
let clocks = rcc.cfgr.hse(HSEClock::new(25.mhz(), HSEClockMode::Bypass)).freeze();
```
* g0xx, g4xx
```rust
let rcc = rcc.freeze(Config::pll().pll_cfg(PllConfig { max: PLLSrc::HSE_BYPASS(8.mhz()), ..Default::default() }));
```
* h7xx
```rust
let ccdr = rcc.use_hse(25.mhz()).bypass_hse().freeze(pwrcfg, &dp.SYSCFG);
```
* l4xx
```rust
let clocks = rcc.cfgr.hse(8.mhz(), CrystalBypass::Disable, ClockSecuritySystem::Disable).freeze(&mut …
```

Add support for HSE bypass and CSS

---

CHANGELOG.md
Cargo.toml
examples/i2c_scanner.rs
src/i2c.rs

* Fix I2C clock
STM32F3 I2C peripherals are clocked by HSI or sysclk, not pclk1
* Support I2C3
I2C3 is available on f301, f318, f302x6/8/d/e, f303xd/e and f398
Also remove I2C2 support on f303x6/8 and f328
* Move I2C implementation out of macro
The big `i2c!` macro makes code less readable and confuses rustfmt, clippy, etc.
Inspired by f7xx-hal

Fix I2C clock and support I2C3

---

README.md
src/delay.rs

I encountered a bit of discovery here, so I figured I'd add some docs while it was fresh in my mind.

Add documentation on how to run tests to the README.

---

CHANGELOG.md
src/can.rs

I know there is an open issue for refactoring the CAN impl (#178) but figured I would patch the existing impl slightly in the meantime.
This fixes an issue where weren't actually transmitting the correct length of data, as well as adding options to allow users to configure the baud rate and enable loopback mode.

Small fixes for CAN

---

CHANGELOG.md
src/delay.rs

Leverage a full 32 bit range instead of only 24 bit range.
This will increase the maximum possible delay from ~2 seconds
up to 9 minutes.
Also cap the value, instead of panicking, if the value is to high.
Fixes https://github.com/stm32-rs/stm32f3xx-hal/issues/203

Increase SysTick delay limit

---

examples/can.rs
examples/i2c_scanner.rs
examples/pwm.rs
examples/serial_dma.rs
examples/spi.rs
examples/usb_serial.rs
src/prelude.rs
tests/rcc.rs

This is a slight ergonomic improvement and keeps
the old behavior.
The user does not have to remember to import
`time::duration::*` just to configure any peripheral.

Add time extension trait to prelude

---

CHANGELOG.md
src/rcc.rs

Make ppre methods public

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/pwm.rs
src/usb.rs

- stm32f3 upgrade removes `stm32f3x8` feature in place of `stm32f303`
- stm32-usbd update removes ram_access_1x16 feature

Bump dependencies

---

CHANGELOG.md
Cargo.toml
codegen/src/codegen/gpio.rs
examples/can.rs
examples/gpio_erased.rs
examples/gpio_interrupts.rs
examples/i2c_scanner.rs
examples/pwm.rs
examples/serial_dma.rs
examples/spi.rs
examples/usb_serial.rs
src/can.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/prelude.rs
src/pwm.rs
src/serial.rs
src/spi.rs
src/syscfg.rs
src/usb.rs

* Simplify macro
`gpio.rs` uses more generics than macro now
* Collapse Input type arguments
An attempt to address #125
* Support interrupt
Close #83 and #112

GPIO refactor (Simplify macro, reduce type states, and support interrupt)

---

src/adc.rs

As explained in issue #206, the code here is doing the calculation completely wrong.  This leads to a multi-second startup delay instead of just a few clock cycles.
Fix this by using the correct calculation; currently only ADC clock configurations synchronous to the AHB are supported which makes this quite easy: We just need to delay the given number of cycles * the selected ADC clock prescaler (1, 2, or 4).
To make this code future proof against an implementation of asynchronous ADC clock configurations, use a `match` statement here which will fail to compile once the `ASYNCHRONOUS` variant is added to the `CkMode` struct - thus forcing the implementor to take another look at this.
Fixes: #206

Fix long delay during ADC initialization

---

README.md

Note: This is not a hard requirement and only exists for documentation
purposes, to avoid confusion.
See https://github.com/stm32-rs/stm32f3xx-hal/issues/218
for example.
This should not prevent anyone to use newer features.
As soon as the MSVR does not compile anymore, just bump it.

Add MSVR notice to README

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
build.rs
examples/can.rs
src/adc.rs
src/can.rs
src/dma.rs
src/lib.rs
src/spi.rs
src/usb.rs

I had some ideas about the newly added build.rs and touched some documentation as well. 
What do you think about this change, @Piroro-hs?

Improve build.rs and some more. 

---

Cargo.toml
src/adc.rs
src/can.rs
src/dma.rs
src/lib.rs
src/rcc.rs
src/usb.rs

Use the unstable [`#[doc(cfg(...))]`](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html) feature. 
It is feature gated by the [`docsrs`](https://docs.rs/about/builds#cross-compiling) feature, so locally no unstable feature is required.
It will look like this:

Show feature gate on docsrs 

---

Cargo.toml
examples/serial_echo_rtic.rs
src/serial.rs

Hi,
This pull request adds Read and Write implementations to Serial and few functions to work with Irq flags.
This needed to add more control under communicaiton flow and timing.
Also I added an example how to use this with RTIC. The example uses DIR pin when transmiting (like RS485).
PS: This is my first pull request ever :)

Add read and write impl for Serial, Irq flags functions and RTIC example

---

src/delay.rs

This makes two changes:
* Updates the MAX_RVR to a 24-bit (not 25-bit) number
* Moves tracking variable update for better potential precision
This brings the stm32f3 delay impl up to date with the [nrf52 delay impl](https://github.com/nrf-rs/nrf-hal/blob/master/nrf-hal-common/src/delay.rs#L46-L72).

Fix off-by-one error in Delay impl

---

CHANGELOG.md
examples/serial_dma.rs
examples/serial_echo_rtic.rs
src/dma.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/rcc.rs
src/serial.rs
testsuite/tests/uart.rs

This requires changing I2C to a more generic implementation,
where the specific UART peripheral implementation get's dispatch
upon it's Instance trait.
The specific UART is longer hard coded into, but instead is referenced
via pointer (trait).
This also allows to reduce the usart macro implementation, so that
the code is easier to follow.
But this leads to code duplication, as code for the Write and Read
trait of embedded-hal can no longer be shared between Serial and Tx |
Rx.
Also, the underlying UART peripheral of Tx and Rx after split has to be
tracked at runtime, instead of being decoded at compile time (via macro).
In addition to all of this the Idle interrupt event was also added.

Allow Serial::new instead of Serial::usartX

---

src/serial.rs

The clear_bit in at the end of the clock enable was
deleted accidentally. This commit re-adds this call.

Fix uart clock initialization

---

CHANGELOG.md
src/timer.rs

This was accidentally removed in #192

Readd MonoTimer

---

CHANGELOG.md
src/gpio.rs

This is appropriate because we only ever perform atomic operations on
these registers.  This allows `PXx` to be Send + Sync.
Closes #249

Mark Gpiox as Send and Sync

---

CHANGELOG.md

Because to implement Serial::join the generic
parameters of Tx and Rx had to be changed from
Tx<Usart> -> Tx<Usart, Pin>

Mark Serial::join as a breaking change

---

CHANGELOG.md
src/serial.rs
testsuite/tests/adc.rs
testsuite/tests/uart.rs
testsuite/tests/watchdog.rs

This is about to add more configuration options like data bits and parity to `Serial`. Baudrate and the new parameters are provided in a struct `Config` which replaces the baud rate parameter of `Serial::new` and could be converted from a baud rate so that it would not break existing code. 
I've created this draft PR to surface this WIP and provide a place for discussion. There is likely more to come and I will rebase my changes once UART refactoring has landed.
Closes #231

Add config struct for Serial

---

CHANGELOG.md
src/usb.rs

The 303xd and 303xe series devices do not have AF14 for pins PA11 and
PA12, so the existing implementation will not work for those devices.
According to an ST document [1], stm32f303xd and xe do not require any
particular mode for the PA11 and PA12 pin, so I've parameterized the
`usb::Peripheral` type using traits so that any mode will be
supported.  I've tried to follow a familiar pattern reminescent of the
gpio alternate function configurations.
This is of course a breaking change so I'm open to other approaches if
anyone has opinions.  This seemed to me to be the most elegant and
accurate way to handle this.
[1]: https://www.st.com/resource/en/application_note/dm00260340-migrating-between-stm32f303-and-stm32f302-line-products-stmicroelectronics.pdf

Support USB on the stm32f303xd/xe devices

---

src/lib.rs

This allows for `#[cfg_attr(docsrs, doc(cfg(...)))]` to properly work.

Enable `feature(doc_cfg)` if `cfg(docsrs)`

---

CHANGELOG.md
examples/gpio_interrupts.rs
examples/serial_echo_rtic.rs
src/adc.rs
src/gpio.rs

Define pin type aliases directly under gpio module

---

CHANGELOG.md
src/serial.rs

The clock tree figures of RM0366, RM0365, RM0364, RM0316, and RM0313 show that the default setting of RCC::CFGR3::USART1SW will, for some variants, make the port use PCLK1 for reference, and not PCLK2 where port is resident.
The affected variants are stm32f3xxx4/6/8, except stm32f37xxx.
This is consistent with my observations on stm32f344r8, which fails to produce the correct baud rate:
- If sysclk is configured above 32 MHz and both pclk are untouched (pclk1 is then divided, but pclk2 is not), or
- If the pclk's are specifically configured differently.
This might be related to #109, although I don't see why the discussed code snippet should cause different pclk's.

USART1 connects to PCLK1.

---

CHANGELOG.md
examples/gpio_interrupts.rs
src/gpio.rs
src/lib.rs
src/syscfg.rs

Rework GPIO interrupt API to be the same as introduced in #253

Gpio interrupt

---

CHANGELOG.md
src/dma.rs

Change DMA interrupt API to be more in line with #253

Dma interrupt

---

CHANGELOG.md
README.md
examples/adc.rs
src/adc.rs
src/i2c.rs
src/lib.rs
src/pwm.rs
src/rtc.rs
src/spi.rs
testsuite/tests/adc.rs

Preparations like introducing `#[non_exhaustive]` to later not having to introduce breaking changes, when improving these modules.
Closes #175 
Closes #169

Breaking Changes for non-complete modules

---

CHANGELOG.md
src/serial.rs

Implement fmt::Write for serial

---

RELEASE_PROCESS.md
release.toml

Set correct cargo release push remote

---

.github/workflows/ci.yml
Cargo.toml

This catches linking errors, which might not be catched otherwise

ci: Use build instead of check

---

Cargo.toml

Workaround the cortex-m -> bare-metal 0.2.1
dependency by depending on bare-metal 0.2.5
directly, as long as
https://github.com/rust-embedded/cortex-m/pull/361
is not fixed.

Fix minimal dependency build

---

CHANGELOG.md
examples/can.rs
src/can.rs
src/rcc.rs
src/serial.rs
src/spi.rs
src/timer/interrupts.rs
testsuite/Cargo.toml
testsuite/tests/uart.rs

Add missing spi impls for gpio-f303

---

CHANGELOG.md
deny.toml
src/spi.rs

This impl was accidentally removed after refactoring
and is a regression at least from previous versions
Fix #320

Add missing MosiPin for PB5

---

CHANGELOG.md
src/adc/config.rs
src/serial.rs
src/serial/config.rs
src/spi/config.rs
testsuite/tests/uart.rs

I tried a small test program on the Discovery board and suffered from receive overflows while polling the serial interface via "uart.read()".
Data rate is 19200 baud and polling interval is about 50-60us, so this shouldn't be possible.
I could fix my problem by the change in this PR
It looks like there is a chance to poll when some data is still in shift register and in the next poll cycle rdr got updated and the start-bit of the next character is already in the shift register. 
This sets isr.busy and read() returns Error::WouldBlock although there is a valid character in rdr.
To test this I added a uart test case to the testsuite, which fails with the original implementation and passes with my fix.
Please let me know, if the PR is invalid, needs a change or if I missed something.
I can …

Fix uart busy handling

---

src/rtc.rs

The functions [`from_ymd`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.from_ymd) and [`and_hms`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.and_hms) were deprecated in 0.4.23 in favour of the `_opt` variants

Update RTC API

---

CHANGELOG.md
src/timer.rs
testsuite/tests/timer.rs

Make the calculation more robust against overflows and wrong settings
Fixes #333

Fix timer panic on high frequencies

---

CHANGELOG.md
src/adc/channel.rs

Fixes https://github.com/stm32-rs/stm32f3xx-hal/issues/344.

Add channel impls for pins PE9 and PE10 when using stm32f303xe feature 

---

CHANGELOG.md
src/timer.rs

Extend ticks calculation in timer start from u32 to u64
